apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{name}}"
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: "{{name}}"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  {{#if ttl}}
  ttl: {{ ttl }}
  {{/if}}
  image: "{{image}}"
  port: 3000
  liveness:
    path: "{{base_path}}/api/internal/isalive"
    initialDelay: 10
  readiness:
    path: "{{base_path}}/api/internal/isready"
    initialDelay: 10
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  env:
    - name: SELF_URL
      value: "{{ingress}}"
    - name: DP_MELDEKORTREGISTER_URL
      value: http://dp-meldekortregister
    - name: DP_PERSONREGISTER_URL
      value: http://dp-rapportering-personregister
    - name: VITE_USE_MSW
      value: "{{use_msw}}"
    - name: VITE_IS_LOCALHOST
      value: "{{is_localhost}}"
    - name: VITE_FARO_URL
      value: "{{faro_url}}"
    - name: RUNTIME_ENVIRONMENT
      value: "{{runtime_environment}}"
    - name: SANITY_DATASETT
      value: "{{sanity_datasett}}"
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
      rules:
        - application: dp-meldekortregister
        - application: dp-rapportering-personregister
        

  azure:
    application:
      tenant: "{{azure.tenant}}"
      enabled: {{azure.enabled}}
      claims:
        groups:
          - id: "{{azure.grupper.saksbehandler}}"
          - id: "{{azure.grupper.beslutter}}"
        extra:
          - NAVident
    sidecar:
      enabled: {{azure.enabled}}
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic