apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-saksbehandling-frontend-pr-{{prNumber}}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-rapportering-saksbehandling-frontend
    pr-preview: "true"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 5173
  liveness:
    path: /api/internal/isalive
    initialDelay: 10
  readiness:
    path: /api/internal/isready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    - https://dp-rapportering-saksbehandling-frontend-pr-{{prNumber}}.ekstern.dev.nav.no
  env:
    - name: BASE_PATH
      value: ""
    - name: SELF_URL
      value: https://dp-rapportering-saksbehandling-frontend-pr-{{prNumber}}.ekstern.dev.nav.no
    - name: DP_MELDEKORTREGISTER_URL
      value: http://dp-meldekortregister
    - name: DP_PERSONREGISTER_URL
      value: http://dp-rapportering-personregister
    - name: VITE_USE_MSW
      value: "true"
    - name: VITE_IS_LOCALHOST
      value: "false"
    - name: VITE_FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: RUNTIME_ENVIRONMENT
      value: pr-preview
    - name: SANITY_DATASETT
      value: "production"  
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
      rules:
        - application: dp-meldekortregister
        - application: dp-rapportering-personregister
  azure:
    application:
      tenant: trygdeetaten.no
      enabled: false
      claims:
        groups:
          - id: ""
          - id: ""
        extra:
          - NAVident
    sidecar:
      enabled: false
      autoLogin: false
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
