apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-saksbehandling-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-rapportering-saksbehandling-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 5173
  liveness:
    path: "{{base_path}}/isalive"
    initialDelay: 10
  readiness:
    path: "{{base_path}}/isready"
    initialDelay: 10
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  secureLogs:
    enabled: true
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: VITE_BASE_PATH
      value: {{base_path}}
    -name: DP_RAPPORTERING_URL
      value: http://dp-rapportering
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: amplitude.nav.no
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: {{idporten.level}}
      autoLogin: true
  tokenx:
    enabled: true
