name: Manual PR Cleanup

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR-nummer å slette (f.eks. "123")'
        required: true
        type: string

jobs:
  cleanup:
    name: Delete PR Preview App
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Login to NAIS
        uses: nais/login@v0
        with:
          team: teamdagpenger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}

      - name: Set NAIS context
        run: |
          kubectl config use-context dev-gcp && kubens teamdagpenger

      - name: Delete NAIS application
        id: delete
        run: |
          APP_NAME="dp-rapportering-saksbehandling-frontend-pr-${{ inputs.pr_number }}"
          echo "Attempting to delete: $APP_NAME"

          if kubectl delete app "$APP_NAME" -n teamdagpenger --ignore-not-found=true; then
            echo "result=success" >> $GITHUB_OUTPUT
            echo "### ✅ Cleanup fullført" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "PR-app \`$APP_NAME\` har blitt slettet fra NAIS." >> $GITHUB_STEP_SUMMARY
          else
            echo "result=failed" >> $GITHUB_OUTPUT
            echo "### ❌ Cleanup feilet" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Kunne ikke slette \`$APP_NAME\`. Se loggen for detaljer." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
