name: Manual PR Cleanup

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR-nummer å slette (f.eks. "123")'
        required: true
        type: string

jobs:
  cleanup:
    name: Delete PR Preview App
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gh-teamdagpenger@nais-management-233d.iam.gserviceaccount.com

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: dev-gcp
          location: europe-north1

      - name: Delete NAIS application
        run: |
          kubectl delete app dp-rapportering-saksbehandling-frontend-pr-${{ inputs.pr_number }} \
            -n teamdagpenger \
            --ignore-not-found=true

      - name: Summary
        if: always()
        run: |
          echo "### Cleanup fullført ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "PR-app \`dp-rapportering-saksbehandling-frontend-pr-${{ inputs.pr_number }}\` har blitt slettet fra NAIS." >> $GITHUB_STEP_SUMMARY
        shell: bash
