name: Comment PR with Preview Link

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  comment-link:
    if: github.event.pull_request.head.repo.fork != true
    name: Comment with Preview Link
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Preview deployment**\n\n✅ https://cdn.nav.no/teamdagpenger/dp-rapportering-saksbehandling-frontend/pr-${{ github.event.pull_request.number }}/index.html'
            })
